name: Build
on:
  jobs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t pico-mruby-dev .

      - name: Build pico-mruby
        run: docker run --mount type=bind,source=$(pwd)/,target=/work pico-mruby-dev /bin/bash -c "mkdir build; cd build; cmake ..; cmake --build .;"
