name: Build

on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  scedule:
    - cron: "0 0 * * *"
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set version
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo "filename=$REPOSITORY" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pico-mruby-dev

      - name: Build pico-mruby
        run: docker run --mount type=bind,source=$(pwd)/,target=/work pico-mruby-dev /bin/bash -c "mkdir build; cd build; cmake ..; cmake --build .;"

      - name: Archive
        run: |
          mkdir binary
          cp build/src/pico_mruby/pico-mruby.uf2 binary
          zip -j -r ${{ steps.version.outputs.filename }}.zip binary

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.version.outputs.filename }}.zip
          path: ./${{ steps.version.outputs.filename }}.zip
