name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_releae:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build the Docker image
        run : docker build . --file Dockerfile --tag pico-mruby-dev

      - name: Build pico-mruby
        run: docker run --mount type=bind,source="$(pwd)"/,target=/work pico-mruby-dev /bin/bash -c "cmake -G Ninja -B build && cmake --build build"

      - name: Archive
        run: |
          mkdir -p ${{ github.workspace }}/binary/hello_world2
          cp build/src/hello_world/hello_world.uf2 ${{ github.workspace }}/binary/hello_world2
          mkdir -p ${{ github.workspace }}/binary/pico_mirb
          cp build/src/pico_mirb/pico-mirb.uf2 ${{ github.workspace }}/binary/pico_mirb
          mkdir -p ${{ github.workspace }}/binary/pico_mruby
          cp build/src/pico_mruby/pico-mruby.uf2 ${{ github.workspace }}/binary/pico_mruby
          zip -j -r ${{ github.event.repository.name }}-${{ github.ref_name }}-binary.zip ${{ github.workspace }}/binary

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{github.ref_name }} --title "Release ${{ github.ref_name }}" -d --generate-notes \
            ./${{ github.event.repository.name }}-${{ github.ref_name }}-binary.zip
